FROM custom-centos-7:latest
MAINTAINER Ruben "rvasallo@leadtech.com"

ENV TERM xterm-256color

#Configure TimeZone
RUN ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime

# Install python
RUN yum install -y \
	python-2.7.* \
	python-devel-2.7.* \
	python-setuptools \
	gcc \
	git

# Install flask
RUN git clone --branch 0.10.1 http://github.com/mitsuhiko/flask.git /flask && \
	cd /flask && \
	python setup.py develop


# Install Devel tools
RUN yum install -y \
	vim 

EXPOSE 5000 
